### ISSUE TITLE
Any luck?

### ISSUE THREAD

**Issue by lopestom** [depesh1977/device_realme_RMX3231#1]
Any luck with TWRP starting in your device?

**Comment by depesh1977** [comment]
No

**Comment by lopestom** [comment]
> No

Send stock files with same version of your device. Specially super.img & boot.img
I'll study and looking something.

**Comment by lopestom** [comment]
I was looking at some files in DT and noticed that there are references where the file is in \system\etc\
So you could modify this. But it may also be that it doesn't interfere with something. Furthermore, I know you are used to copying files directly and before, it even worked. So I think many parts written in the file don't work and should be "cleaned". This would eliminate some startup doubt.
https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L305

https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L368

For example: Does TWRP really need this part?
https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L70

**Comment by lopestom** [comment]
This DT: https://github.com/depesh1977/Realme/tree/android-11
not work?

**Comment by RadGoodNowYT** [comment]
> I was looking at some files in DT and noticed that there are references where the file is in \system\etc So you could modify this. But it may also be that it doesn't interfere with something. Furthermore, I know you are used to copying files directly and before, it even worked. So I think many parts written in the file don't work and should be "cleaned". This would eliminate some startup doubt.
> 
> https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L305
> 
> https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L368
> 
> For example: Does TWRP really need this part?
> 
> https://github.com/depesh1977/device_realme_RMX3231/blob/08480c593ec6119851b3921c34209602ba64ab19/recovery/root/init.recovery.common.rc#L70

i have exactly these lines in my init.rc and twrp still starts. I guess there's something with fstab.
`[    8.520410] init: Service 'recovery' (pid 288) received signal 6
[    8.520440] init: Sending signal 9 to service 'recovery' (pid 288) process group...`

`[   11.228403] WCN BASE error: try open file /dev/block/platform/soc/soc:ap-ahb/20600000.sdio/by-name/gpsgl_a,count_num:7, file=        (ptrval)
[   11.228929] type=1400 audit(1704564268.139:48): avc: denied { search } for comm="kworker/4:0" name="block" dev="tmpfs" ino=10263 scontext=u:r:kernel:s0 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0`
That's what was in his logs
He should try run TWRP without fstab or at least without /data partition writed there. Just comment it #. Maybe will work because it worked for me when I edited something related to /data partition in fstab. But we also removed androidboot.selinux=permissive from being applied to boot.img cmdline. It's sad that there is no info in internet about these issues so we have to find out solution for problem ourselves

**Comment by lopestom** [comment]
> But we also removed androidboot.selinux=permissive from being applied to boot.img cmdline. It's sad that there is no info in internet about these issues so we have to find out solution for problem ourselves

Since Android 11 shipped with new devices, enthusiasts with Custom Recovery have had this issue as well. But that was more than 3 years ago.
Yes, we communicate about this. In fact, anyone who was interested in Custom Recovery and Custom ROM knew this and was able to fix it easily. Well, that was rightly said as `Enforcing` in the SeLinux part.
Yes, the `permissive` part can be in the cmdline, but the kernel can be programmed to respond only to what the company wanted or has put in programming/permission lines.

So those who are new to this generally haven't studied it or haven't really wanted to look into it.

---

I am creating a device tree based on the information I have about Unisoc. But I don't know if it will work.

I'm doing this little by little. It is always necessary to read the SPRD source code.

So what can be said is that even if they do this or that, what exists is the correction/fixing of the encryption/decryption part.
It will be interesting to delve deeper into this and make it work.
We know that until Android 11, the firmware system can support `encryptable`, but this is something to have as a plan B.

I saw few people trying to fix functional encryption on SPD/Unisoc devices, especially on Android 9 and 10 version.
So before they played with `encryptable` and everything was fine. Of course, there are still `updates/fixes/solutions` to the TWRP source code from TeamWin. Generally this can take longer than we can be patient with.

At this point I want to help @depesh1977 , especially with tests. But the main thing is to have TWRP start normally.

Wait on that.

**Comment by lopestom** [comment]
> i have exactly these lines in my init.rc and twrp still starts. I guess there's something with fstab. `[ 8.520410] init: Service 'recovery' (pid 288) received signal 6 [ 8.520440] init: Sending signal 9 to service 'recovery' (pid 288) process group...`
> 
> `[ 11.228403] WCN BASE error: try open file /dev/block/platform/soc/soc:ap-ahb/20600000.sdio/by-name/gpsgl_a,count_num:7, file= (ptrval) [ 11.228929] type=1400 audit(1704564268.139:48): avc: denied { search } for comm="kworker/4:0" name="block" dev="tmpfs" ino=10263 scontext=u:r:kernel:s0 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0`

Okay. `permissive` is not set.
Have same message or that's not appears?

about `try open file /dev/block/platform/soc/soc:ap-ahb/20600000.sdio/by-name/gpsgl_a,count_num:7,` so it's from blkdio device like `androidboot.boot_devices=soc/soc:ap-ahb/20600000.sdio`

But I think about gps / `gpsgl_a` go from https://github.com/depesh1977/device_realme_RMX3231/blob/2f44cd4412e31d18f3b8bc49b7b91ed05f81c7a1/recovery/root/init.recovery.common.rc#L70

So without that binary file putted in the `\vendor\bin` so can have errors...... Obviusly not need gps binary file to TWRP....

**Comment by depesh1977** [comment]
> > No
> 
> Send stock files with same version of your device. Specially super.img & boot.img I'll study and looking something.

[https://mega.nz/file/V1Ei1JQK#uQxsLXd84X9tMEZM9gcMQWuzakX_StzI-OrrkBHxmw4]boot.img(url)

**Comment by depesh1977** [comment]
[dmesg.zip](https://github.com/depesh1977/device_realme_RMX3231/files/13881331/dmesg.zip)

**Comment by depesh1977** [comment]
[https://mega.nz/file/95NRFZYT#S-NSKG0mm4LPUHxwW2u3tlBjrSjmQ-mnHZT95UI9Myc](url)
super.img

**Comment by lopestom** [comment]
> > > No
> > 
> > 
> > Send stock files with same version of your device. Specially super.img & boot.img I'll study and looking something.
> > [https://mega.nz/file/V1Ei1JQK#uQxsLXd84X9tMEZM9gcMQWuzakX_StzI-OrrkBHxmw4](url)
> > boot.img

I send invite to my repository. Soong I'll upload files to compile img file.

**Comment by Abaza009** [comment]
Идут продвижения по этому вопросу?
